# Classification Using Tree

In [8]:
from sklearn import tree
import numpy as np
import pandas as pd

In [9]:
X= np.random.randint(50, 150, size=(10, 3))

In [10]:
X[:,0]*=8
X[:,1]*=2
X[:,2]*=1
print(X)

[[ 656  130   94]
 [ 632  142  108]
 [1088  240   86]
 [ 832  290  128]
 [ 488  136   91]
 [ 416  222  135]
 [ 976  214   53]
 [ 552  128  130]
 [ 616  114  121]
 [1184  260   85]]


In [11]:
Y=np.random.choice(['M','F'], size=10)
print(Y)

['M' 'M' 'M' 'M' 'F' 'F' 'F' 'M' 'M' 'F']


In [15]:
clf=tree.DecisionTreeClassifier()
clf=clf.fit(X,Y)

In [17]:
prediction=clf.predict([[616,114,121]])
print(prediction)

['M']


# NearestCentroid Classifier

In [19]:
from sklearn.neighbors.nearest_centroid import NearestCentroid
clf.fit(X, Y)
NearestCentroid(metric='euclidean', shrink_threshold=None)
print(clf.predict([[616,114,121]]))

['M']


# Classification Using LogisticRegression

In [20]:
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()
logmodel.fit(X,Y)
predictions=logmodel.predict([[616,114,121]])
print(predictions)

/home/yp/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


['M']


/home/yp/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


# K-means classification

In [22]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
print(kmeans.labels_)
kmeans.predict([ [616, 114, 121], [1184, 260, 85]])

[0 0 1 1 0 0 1 0 0 1]


array([0, 1], dtype=int32)